---

server:
  port: 8680

spring:
  data:
    cassandra:
      cluster-name: Test Cluster
      keyspace-name: rentaltrucks
      username: cassandra
      password: cassandra
      schema-action: recreate_drop_unused
