INSERT INTO rentaltrucks.truck_types (truck_type, truck_make, truck_model) VALUES ('conversion van', 'Dodge', 'ConversionVan');
INSERT INTO rentaltrucks.truck_types (truck_type, truck_make, truck_model) VALUES ('15 foot truck', 'Dodge', 'Truck15');
INSERT INTO rentaltrucks.truck_types (truck_type, truck_make, truck_model) VALUES ('20 foot truck', 'Dodge', 'Truck20');
INSERT INTO rentaltrucks.truck_types (truck_type, truck_make, truck_model) VALUES ('26 foot truck', 'Dodge', 'Truck26');
